### ISSUE TITLE
ValueError: Wallpaper does not exist even when I don't want to change the wallpaper

### ISSUE THREAD

**Issue by notalexnot** [justjokiing/kshift#15]
Hi again!

https://github.com/justjokiing/kshift/blob/e772af8a9cd4f679c186edb2f7d3eab3548e93dd/src/theme.py#L36

While trying to install kshift, even if I comment the `wallpaper`  variable (or leave it empty) in `defaults.yml`, I get the following error: `ValueError: Wallpaper does not exist: /usr/share/wallpapers/Flow/contents/images/5120x2880.jpg` because my distro (openSUSE) doesn't have that path. I'm not sure if the path to wallpapers is standardized in the environment across distros, but it would be easier to use an environment variable, even though it should be skipped.

Btw, I don't have enough time right now to debug more, but I think the problem is that it defaults to the default configuration, instead of declaring wallpaper as `None` since i can declare it manually and it works :eyes:

**Comment by justjokiing** [comment]
I just removed the default wallpaper from being hard coded. It should not have made the assumption that every distro would have it. It should be fixed the in the most recent commit. Please let me know

**Comment by notalexnot** [comment]
Hello, I still got an error if I leave the `wallpaper` variable empty (or comment it) in the `defaults.yml`: 

```python
Traceback (most recent call last):
  File "/PATH/kshift/src/./kshift", line 34, in <module>
    t = theme.Theme(name, colorscheme, icontheme, wallpaper, command, ti, enabled )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PATH/kshift/src/theme.py", line 36, in __init__
    raise ValueError(f"Wallpaper does not exist: {wallpaper}")
ValueError: Wallpaper does not exist: None
```

But I think I found the problem in:

https://github.com/justjokiing/kshift/blob/4dda9473d9b1840e5ba3afdf9fbdea971dbee88e/src/theme.py#L70-L71

If you print the type of wallpaper before the comparison in: 

https://github.com/justjokiing/kshift/blob/4dda9473d9b1840e5ba3afdf9fbdea971dbee88e/src/theme.py#L33-L34

You get a: `<class 'str'>` instead of a: `<class 'NoneType'>`. But because of the code and some comparisons, even if the value is converted to a NoneType, you'll find more errors because you can't run `os.path.exists` with a NoneType and so.

I tried debugging more, but I'm busy with homework right now. 😟

**Comment by notalexnot** [comment]
Btw, my temporary solution was to declare `wallpaper = None` just before the:

https://github.com/justjokiing/kshift/blob/4dda9473d9b1840e5ba3afdf9fbdea971dbee88e/src/theme.py#L33-L36

**Comment by justjokiing** [comment]
Sorry for the very late response. kshift now has a new release, please update and let me know if there are any more issues.
