### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by hrqmonteiro** [justjokiing/kshift#9]
```
kshift/src on  main via 🐍 v3.11.6 took 8s   ./kshift --install
Traceback (most recent call last):
  File "/home/hrq/kshift/src/./kshift", line 6, in <module>
    import conf
  File "/home/hrq/kshift/src/conf.py", line 5, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```

![image](https://github.com/justjokiing/kshift/assets/17055027/d467cf78-45bb-424c-97ef-0137fa88ae5f)

**Comment by justjokiing** [comment]
You'll have to install colorama to your system. Most likely will be through pip or your package manager.
